[releng] corrected logic to detect that M RC builds are in milestones repository

diff --git a/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.php.template b/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.php.template
--- a/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.php.template
+++ b/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.php.template
@@ -233,105 +233,105 @@ relating to its results and unit tests.
 
   $boxes=calcTestConfigsRan($testResultsDirName);
   if ($boxes < 0 ) { 
-        $boxesDisplay = 0;
+    $boxesDisplay = 0;
   } else {
-        $boxesDisplay = $boxes;
+    $boxesDisplay = $boxes;
   }
-  
+
   echo "<ul class='midlist'>";
   /* We'll always display link to logs (as normal link, not using color:inherit;) */
   echo "<li>View the <a  style=\"text-decoration:none\" title=\"Link to logs.\" href=\"testResults.php\">logs for the current build</a>.</li>\n";
 
   $testResultsStatus = "%testsStatus%";
-  
 
-    /* -3 is special code meaning no testResults directory exists yet. */
-    if (($boxes == -3) || ($testResultsStatus === "pending"))   {  
-        $linkColor = 'inherit';
-        echo "<li>Tests are pending. </li>\n";
-        }
-    else { 
-        if ($testResultsStatus === "successful") {
-            $linkColor = 'green';
-        }   
-        elseif ($testResultsStatus === "failed") {
-            /* note we don't override 'inherit' cases, just 'failed' cases. */
-            if (file_exists("overrideTestColor")) {
-                $linkColor='green';
-            } else {
-                $linkColor = 'red';
-            }   
-        }   
-        else {
-            /* This is a fall-through, unexpected case ... just in case testResultsStatus is something we don't expect. */
-            $testColor='inherit';
-        }   
-        echo "<li>View the <a  style=\"color:${linkColor};text-decoration:none\" title=\"Link test results.\" href=\"testResults.php\">test results for the current build.</a>\n";
+
+  /* -3 is special code meaning no testResults directory exists yet. */
+  if (($boxes == -3) || ($testResultsStatus === "pending"))   {  
+    $linkColor = 'inherit';
+    echo "<li>Tests are pending. </li>\n";
+  }
+  else { 
+    if ($testResultsStatus === "successful") {
+      $linkColor = 'green';
     }   
+    elseif ($testResultsStatus === "failed") {
+      /* note we don't override 'inherit' cases, just 'failed' cases. */
+      if (file_exists("overrideTestColor")) {
+        $linkColor='green';
+      } else {
+        $linkColor = 'red';
+      }   
+    }   
+    else {
+      /* This is a fall-through, unexpected case ... just in case testResultsStatus is something we don't expect. */
+      $testColor='inherit';
+    }   
+    echo "<li>View the <a  style=\"color:${linkColor};text-decoration:none\" title=\"Link test results.\" href=\"testResults.php\">test results for the current build.</a>\n";
+  }   
 
   echo "<table class=testTable>\n";
   echo "<caption>".$boxesDisplay." of ".count($expectedTestConfigs)." test configurations are complete.</caption> \n";
   echo "<tr>";
   echo "<th style=\"width:20%\">Tested Platform</th><th>Failed</th><th>Passed</th><th>Skipped</th><th>Total</th><th>Test&nbsp;Time&nbsp;(s)</th>\n";
-    
-    foreach ($expectedTestConfigs as $config) {
-        
-        if (isset($testResults[$config])) {
-            $testRes = $testResults[$config];
-            $failed = $testRes['failCount'];
-            $passed = $testRes['passCount'];
-            $skipped = $testRes['skipCount'];
-            $total = $failed + $passed + $skipped;
-            $duration = $testRes['duration'];
-            if (file_exists("overrideTestColor")) {
-                $linkColor='green';
-            }   
-            else {
-                if ($failed > 0) {
-                    /* note we don't override  'inherit' cases, just 'failed'. */
-                    if (file_exists("overrideTestColor")) {
-                        $linkColor='green';
-                    } else {
-                        $linkColor = 'red';
-                    }   
-                } else {
-                    $linkColor='green';
-                }   
-            }   
-            echo "<tr>\n";
-            echo "<td style=\"text-align:left\">\n";
-            echo "<a style=\"color:${linkColor};text-decoration:none\" href=\"testResults.php\">".$config."</a>";
-            echo "</td>\n";
-            echo "<td>$failed</td><td>$passed</td><td>$skipped</td><td>$total</td><td>$duration</td>\n";
-            echo "</tr>\n";
-        }   
-        else {
-            /* Yes, all configs intentionally links, since all go to the same place, but if no results yet, would not look like one. */
-            $linkColor = 'inherit'; 
-            echo "<tr>\n";
-            echo "<td style=\"text-align:left\">\n";
-            echo "<a style=\"color:${linkColor};text-decoration:none\" href=\"testResults.php\">".$config."</a>";
-            echo "</td>\n";
-            echo "<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>\n";
-            echo "</tr>\n";
-        }   
-    }   
-     echo "</table>\n";
-    /* table is contained in last link item */
-    echo "</li>\n";
-    echo "</ul>\n";
-    echo "</div>\n";
 
-    // if (file_exists("performance/performance.php")) {
-    // echo "<li>";
-    // $generated=file_exists("performance/global_fp.php");
-    // if (!$generated) 
-    // {
-    //   echo "<i>";
-    //   echo "<a href=\"performance/performance.php\">View the <b>performance results</b> for the current build.</a>";
-    //   if (!$generated) echo "</i>";
-    // echo "</li>";
-    // }
+  foreach ($expectedTestConfigs as $config) {
+
+    if (isset($testResults[$config])) {
+      $testRes = $testResults[$config];
+      $failed = $testRes['failCount'];
+      $passed = $testRes['passCount'];
+      $skipped = $testRes['skipCount'];
+      $total = $failed + $passed + $skipped;
+      $duration = $testRes['duration'];
+      if (file_exists("overrideTestColor")) {
+        $linkColor='green';
+      }   
+      else {
+        if ($failed > 0) {
+          /* note we don't override  'inherit' cases, just 'failed'. */
+          if (file_exists("overrideTestColor")) {
+            $linkColor='green';
+          } else {
+            $linkColor = 'red';
+          }   
+        } else {
+          $linkColor='green';
+        }   
+      }   
+      echo "<tr>\n";
+      echo "<td style=\"text-align:left\">\n";
+      echo "<a style=\"color:${linkColor};text-decoration:none\" href=\"testResults.php\">".$config."</a>";
+      echo "</td>\n";
+      echo "<td>$failed</td><td>$passed</td><td>$skipped</td><td>$total</td><td>$duration</td>\n";
+      echo "</tr>\n";
+    }   
+    else {
+      /* Yes, all configs intentionally links, since all go to the same place, but if no results yet, would not look like one. */
+      $linkColor = 'inherit'; 
+      echo "<tr>\n";
+      echo "<td style=\"text-align:left\">\n";
+      echo "<a style=\"color:${linkColor};text-decoration:none\" href=\"testResults.php\">".$config."</a>";
+      echo "</td>\n";
+      echo "<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>\n";
+      echo "</tr>\n";
+    }   
+  }   
+  echo "</table>\n";
+  /* table is contained in last link item */
+  echo "</li>\n";
+  echo "</ul>\n";
+  echo "</div>\n";
+
+  // if (file_exists("performance/performance.php")) {
+  // echo "<li>";
+  // $generated=file_exists("performance/global_fp.php");
+  // if (!$generated) 
+  // {
+  //   echo "<i>";
+  //   echo "<a href=\"performance/performance.php\">View the <b>performance results</b> for the current build.</a>";
+  //   if (!$generated) echo "</i>";
+  // echo "</li>";
+  // }
 ?>
 
 <div class="homeitem3col">
@@ -342,20 +342,20 @@ relating to its results and unit tests.
 <li><a href="http://wiki.eclipse.org/Platform-releng/How_to_check_integrity_of_downloads">How to verify a download.</a></li>
 
 <?php
-    # place holder: we don't currently produce these reports, and
-    # when we do, will need some work here.
-    # FWIW, we may want to construct elaborate query into CGit for this,
-    # even though that'd be elaborate, would get user to an area where
-    # they coudl tweak query, if desired?
-    if (file_exists("report.txt")) {
-      echo "<p><a href=\"report.txt\">Report of changes</a> from previous build.</p>";
-    }
+  # place holder: we don't currently produce these reports, and
+  # when we do, will need some work here.
+  # FWIW, we may want to construct elaborate query into CGit for this,
+  # even though that'd be elaborate, would get user to an area where
+  # they coudl tweak query, if desired?
+  if (file_exists("report.txt")) {
+    echo "<p><a href=\"report.txt\">Report of changes</a> from previous build.</p>";
+  }
 ?>
 
 <?php
-    if (file_exists("buildnotes/")) {
-      echo "<li><a href=\"buildNotes.php\">View build notes for the current build.</a></li>";
-    }
+  if (file_exists("buildnotes/")) {
+    echo "<li><a href=\"buildNotes.php\">View build notes for the current build.</a></li>";
+  }
 ?>
 </ul>
 </div>
@@ -365,55 +365,55 @@ relating to its results and unit tests.
 
 <?php
 
-    function column($servername) {
+  function column($servername) {
 
-      echo "<td width=\"7%\"><b>Download</b></td>";
-      echo "<td width=\"7%\"><b>Size</b></td>";
-      echo "<td width=\"37%\"><b>File</b></td>";
-      echo "<td width=\"11%\"><b>Checksum</b></td>";
-      return;
+    echo "<td width=\"7%\"><b>Download</b></td>";
+    echo "<td width=\"7%\"><b>Size</b></td>";
+    echo "<td width=\"37%\"><b>File</b></td>";
+    echo "<td width=\"11%\"><b>Checksum</b></td>";
+    return;
+  }
+
+  function getDropSize($zipfile) {
+
+    $filesize = "N/A";
+    $filesizebytes  = filesize($zipfile);
+    if($filesizebytes > 0) {
+      if($filesizebytes < 1048576)
+        $filesize = round($filesizebytes / 1048576, 2) . " MB";
+      else if ($filesizebytes >= 1048576 && $filesizebytes < 10485760)
+        $filesize = round($filesizebytes / 1048576, 1) . " MB";
+      else
+        $filesize = round($filesizebytes / 1048576, 0) . " MB";
     }
+    return($filesize);
+  }
 
-    function getDropSize($zipfile) {
+  function genLinks($servername,$BUILD_ID,$zipfile) {
 
-      $filesize = "N/A";
-      $filesizebytes  = filesize($zipfile);
-      if($filesizebytes > 0) {
-        if($filesizebytes < 1048576)
-          $filesize = round($filesizebytes / 1048576, 2) . " MB";
-        else if ($filesizebytes >= 1048576 && $filesizebytes < 10485760)
-          $filesize = round($filesizebytes / 1048576, 1) . " MB";
-        else
-          $filesize = round($filesizebytes / 1048576, 0) . " MB";
-      }
-      return($filesize);
-    }
+    global $clickthroughstr;
+    global $BUILD_DIR_SEG;
 
-    function genLinks($servername,$BUILD_ID,$zipfile) {
+    $httplink = "$clickthroughstr$zipfile";
+    $httplabel = "(http)";
+    $httpline =  "<div align=\"left\"><a href=\"$httplink\">$httplabel</a>";
+    $filesize = getDropSize($zipfile);
 
-      global $clickthroughstr;
-      global $BUILD_DIR_SEG;
-
-      $httplink = "$clickthroughstr$zipfile";
-      $httplabel = "(http)";
-      $httpline =  "<div align=\"left\"><a href=\"$httplink\">$httplabel</a>";
-      $filesize = getDropSize($zipfile);
-
-      echo "$httpline";
-      echo "&nbsp;&nbsp;";
-      echo "<td>$filesize</td>";
-      echo "<td>$zipfile</td>";
-      // make relative so works on build.eclipse.org -- should not be relative. link to checksum should be absolute, so a "mirror" could not change it,
-      // bsed on changes it made to the package.
-      // TODO: can make some future variables so it has one value on "build" server, and another value on
-      // downloads, such as in buildproperties.php (value would get changed in "promtoe" script).
-      // Also handy/needed when doing "local test builds".
-      // Remember, md5 and sha1 are still in "checksum" directory, for at least initial Luna release, just not linked to. See bug
-      // https://bugs.eclipse.org/bugs/show_bug.cgi?id=423714
-      echo "<td><a href=\"http://download.eclipse.org/eclipse/downloads/drops4/$BUILD_DIR_SEG/checksum/$zipfile.sha512\">[SHA512]</a></td>";
-      //echo "<td><a href=\"./checksum/$zipfile.md5\">(md5)</a>";
-      //echo " <a href=\"./checksum/$zipfile.sha1\">(sha1)</a>";
-    }
+    echo "$httpline";
+    echo "&nbsp;&nbsp;";
+    echo "<td>$filesize</td>";
+    echo "<td>$zipfile</td>";
+    // make relative so works on build.eclipse.org -- should not be relative. link to checksum should be absolute, so a "mirror" could not change it,
+    // bsed on changes it made to the package.
+    // TODO: can make some future variables so it has one value on "build" server, and another value on
+    // downloads, such as in buildproperties.php (value would get changed in "promtoe" script).
+    // Also handy/needed when doing "local test builds".
+    // Remember, md5 and sha1 are still in "checksum" directory, for at least initial Luna release, just not linked to. See bug
+    // https://bugs.eclipse.org/bugs/show_bug.cgi?id=423714
+    echo "<td><a href=\"http://download.eclipse.org/eclipse/downloads/drops4/$BUILD_DIR_SEG/checksum/$zipfile.sha512\">[SHA512]</a></td>";
+    //echo "<td><a href=\"./checksum/$zipfile.md5\">(md5)</a>";
+    //echo " <a href=\"./checksum/$zipfile.sha1\">(sha1)</a>";
+  }
 ?>
 
 <table align="left" BORDER=0 CELLSPACING=5 CELLPADDING=2 WIDTH="100%">
@@ -425,11 +425,22 @@ relating to its results and unit tests.
 <?php
 
 
-    // We expect $BUILD_ID to be defined in buildproperties.php
-    // But it can be defined several times in reference URI, such as once in directory name,
-    // and once in filename. We want the directory-like part.
-    // And to complicate things, in S and R builds, the segment is no longer BUILD_ID,
-    // but a more complicated concatination.
+  $pos = strpos($BUILD_ID, "RC");
+  if ($pos === false) {
+    $isRC = false;
+  } else {
+    $isRC = true;
+  }
+
+  // We expect $BUILD_ID to be defined in buildproperties.php
+  // But it can be defined several times in reference URI, such as once in directory name,
+  // and once in filename. We want the directory-like part.
+  // And to complicate things, in S and R builds, the segment is no longer BUILD_ID,
+  // but a more complicated concatination.
+  if ($BUILD_TYPE === "M" && $isRC ) { 
+    $STREAM_REPO_NAME=$STREAM_MAJOR.".".$STREAM_MINOR."milestones";
+  }   
+  else {
     if ($BUILD_TYPE === "N" || $BUILD_TYPE === "I" || $BUILD_TYPE === "M" || $BUILD_TYPE === "P" || $BUILD_TYPE === "X" || $BUILD_TYPE === "Y") {
       $STREAM_REPO_NAME=$STREAM_MAJOR.".".$STREAM_MINOR."-".$BUILD_TYPE."-"."builds";
     } else {
@@ -446,49 +457,42 @@ relating to its results and unit tests.
         }
       }
     }
+  }
+  $STREAM_REPO_URL="http://download.eclipse.org/eclipse/updates/".$STREAM_REPO_NAME;
 
-    $STREAM_REPO_URL="http://download.eclipse.org/eclipse/updates/".$STREAM_REPO_NAME;
-
-    $pos = strpos($BUILD_ID, "RC");
-    if ($pos === false) {
-      $isRC = false;
+  // There are two types of M builds, some RCs, some not.
+  if ($BUILD_TYPE === "N" || $BUILD_TYPE === "I" || $BUILD_TYPE === "P" || $BUILD_TYPE === "X" || $BUILD_TYPE === "Y" || ($BUILD_TYPE === "M" && ! $isRC)) {
+    $BUILD_REPO_NAME=$STREAM_REPO_NAME."/".$BUILD_ID;
+  } else {
+    $timestamp = str_replace('-', '', $TIMESTAMP);
+    if ($BUILD_TYPE === "S" || $BUILD_TYPE === "R" || ($BUILD_TYPE === "M" && $isRC)) {
+      $BUILD_REPO_NAME=$STREAM_REPO_NAME."/".$BUILD_TYPE."-".$BUILD_ID."-".$timestamp;
     } else {
-      $isRC = true;
-    }
-
-    // There are two types of M builds, some RCs, some not.
-    if ($BUILD_TYPE === "N" || $BUILD_TYPE === "I" || $BUILD_TYPE === "P" || $BUILD_TYPE === "X" || $BUILD_TYPE === "Y" || ($BUILD_TYPE === "M" && ! $isRC)) {
+      echo "Unexpected value of BUILD_TYPE: $BUILD_TYPE. <br />\n";
+      // We will make an assumption that might work.
       $BUILD_REPO_NAME=$STREAM_REPO_NAME."/".$BUILD_ID;
-    } else {
-      $timestamp = str_replace('-', '', $TIMESTAMP);
-      if ($BUILD_TYPE === "S" || $BUILD_TYPE === "R" || ($BUILD_TYPE === "M" && $isRC)) {
-        $BUILD_REPO_NAME=$STREAM_REPO_NAME."/".$BUILD_TYPE."-".$BUILD_ID."-".$timestamp;
-      } else {
-        echo "Unexpected value of BUILD_TYPE: $BUILD_TYPE. <br />\n";
-        // We will make an assumption that might work.
-        $BUILD_REPO_NAME=$STREAM_REPO_NAME."/".$BUILD_ID;
-      }
     }
+  }
 
-    $BUILD_REPO_URL="http://download.eclipse.org/eclipse/updates/".$BUILD_REPO_NAME;
-    // checking for existence is especially important for BUILD_REPOs, since they might have been removed.
-    // but we do it here too for sanity check.
-    // relative patch can be either 3 or 4 "up", depending on if on downloads, or build machine.
-    // either can be used to "prove existance".
-    $relativePath4="../../../..";
-    $relativePath3="../../..";
-    if ((file_exists("$relativePath3/updates/".$STREAM_REPO_NAME)) || (file_exists("$relativePath4/updates/".$STREAM_REPO_NAME))) {
-      echo "<tr> \n";
-      echo "<p>To update your Eclipse installation to this development stream, you can use the software repository at<br />\n";
-      echo "&nbsp;&nbsp;<a href=\"$STREAM_REPO_URL\">$STREAM_REPO_URL</a><br />\n";
-      echo "</tr> \n";
-    }
-    if ((file_exists("$relativePath3/updates/"."$BUILD_REPO_NAME")) || (file_exists("$relativePath4/updates/"."$BUILD_REPO_NAME")) ) {
-      echo "<tr> \n";
-      echo "<p>To update your build to use this specific build, you can use the software repository at<br />\n";
-      echo "&nbsp;&nbsp;<a href=\"$BUILD_REPO_URL\">$BUILD_REPO_URL</a><br />\n";
-      echo "</tr> \n";
-    }
+  $BUILD_REPO_URL="http://download.eclipse.org/eclipse/updates/".$BUILD_REPO_NAME;
+  // checking for existence is especially important for BUILD_REPOs, since they might have been removed.
+  // but we do it here too for sanity check.
+  // relative patch can be either 3 or 4 "up", depending on if on downloads, or build machine.
+  // either can be used to "prove existance".
+  $relativePath4="../../../..";
+  $relativePath3="../../..";
+  if ((file_exists("$relativePath3/updates/".$STREAM_REPO_NAME)) || (file_exists("$relativePath4/updates/".$STREAM_REPO_NAME))) {
+    echo "<tr> \n";
+    echo "<p>To update your Eclipse installation to this development stream, you can use the software repository at<br />\n";
+    echo "&nbsp;&nbsp;<a href=\"$STREAM_REPO_URL\">$STREAM_REPO_URL</a><br />\n";
+    echo "</tr> \n";
+  }
+  if ((file_exists("$relativePath3/updates/"."$BUILD_REPO_NAME")) || (file_exists("$relativePath4/updates/"."$BUILD_REPO_NAME")) ) {
+    echo "<tr> \n";
+    echo "<p>To update your build to use this specific build, you can use the software repository at<br />\n";
+    echo "&nbsp;&nbsp;<a href=\"$BUILD_REPO_URL\">$BUILD_REPO_URL</a><br />\n";
+    echo "</tr> \n";
+  }
 ?>
 
 </table>
